### ISSUE TITLE
Websocket Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by centratelemedia** [lesismal/nbio#182]
try running websocket server, and access from web browser with "Simple Websocket Client" plugin, i got error something like this

``` 
2022/03/29 00:41:46.502 [ERR] conn execute failed: websocket: request origin not allowed by Upgrader.CheckOrigin
goroutine 25 [running]:
github.com/lesismal/nbio.(*Conn).Execute.func1.1.1()
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/conn.go:83 +0x72
panic({0x644e20, 0xc000012ed0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
main.onWebsocket({0x6f6200, 0xc000060000}, 0xc0000a4300)
        /home/joko/projects/go/servergps/websocket_server.go:95 +0x129
net/http.HandlerFunc.ServeHTTP(0x0?, {0x6f6200?, 0xc000060000?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x6f6200, 0xc000060000}, 0xc0000a4300)
        /usr/local/go/src/net/http/server.go:2462 +0x149
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/nbhttp/processor.go:239 +0x3f
github.com/lesismal/nbio.(*Conn).Execute.func1.1(0x0?)
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/conn.go:87 +0x3e
github.com/lesismal/nbio.(*Conn).Execute.func1()
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/conn.go:88 +0x3e
github.com/lesismal/nbio/taskpool.(*MixedPool).callWitoutRecover(0x0?, 0x0?)
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/taskpool/mixedpool.go:38 +0x59
github.com/lesismal/nbio/taskpool.(*MixedPool).Go.func1()
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/taskpool/mixedpool.go:45 +0x36
created by github.com/lesismal/nbio/taskpool.(*MixedPool).Go
        /home/joko/go/pkg/mod/github.com/lesismal/nbio@v1.2.15/taskpool/mixedpool.go:44 +0xcd

```

i try to add header Origin like below, but nothing change, howto control origin?

```


func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := newUpgrader()
	//upgrader.CheckOrigin(r)
	headers := http.Header{}
	headers.Add("Access-Control-Allow-Origin", "*")
	_, err := upgrader.Upgrade(w, r, headers)
	if err != nil {
		panic(err)
	}
}
```

**Comment by lesismal** [comment]
same as this: https://stackoverflow.com/questions/65034144/how-to-add-a-trusted-origin-to-gorilla-websockets-checkorigin

for more details, please refer to the default `CheckOrigin` implementation:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L633

or if you just want allow all host, you can set the `CheckOrigin` handler yourself:
```golang
func newUpgrader() *websocket.Upgrader {
	u := websocket.NewUpgrader()
	// ...

	// allow all host
	u.CheckOrigin = func(r *http.Request) bool {
		return true
	}

	return u
}
```

**Comment by centratelemedia** [comment]
@lesismal  thank you very much work well
