### ISSUE TITLE
Crash on exit when using IOModMixed

### ISSUE THREAD

**Issue by om26er** [lesismal/nbio#253]
My code is using NBIO server, and I recently started playing with IOModMixed. Now when I try to stop my main process, I see below
```
2023/01/03 03:36:16 Starting router 
2023/01/03 03:36:16 Added realm: realm1
2023/01/03 03:36:16.841 [INF] NBIO[oriconn] start
2023/01/03 03:36:16.841 [INF] Serve  NonTLS On: [tcp@[::]:8080]
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6c4087]

goroutine 85 [running]:
github.com/lesismal/nbio/nbhttp.(*Engine).AddConnNonTLSNonBlocking(0xc0001a6090, {0x0, 0x0}, 0x0?, 0x0?)
	/home/om26er/go/pkg/mod/github.com/lesismal/nbio@v1.3.8/nbhttp/engine.go:566 +0x347
github.com/lesismal/nbio/nbhttp.(*Engine).listen.func1()
	/home/om26er/go/pkg/mod/github.com/lesismal/nbio@v1.3.8/nbhttp/engine.go:273 +0x185
created by github.com/lesismal/nbio/nbhttp.(*Engine).listen
	/home/om26er/go/pkg/mod/github.com/lesismal/nbio@v1.3.8/nbhttp/engine.go:265 +0x105
```

**Comment by lesismal** [comment]
I just make a new commit, please try this:
https://github.com/lesismal/nbio/commit/5855926ba2951b839777cb30471bc2a1709748c5

**Comment by lesismal** [comment]
released: https://github.com/lesismal/nbio/releases/tag/v1.3.9

**Comment by om26er** [comment]
Thanks, fixed
