### ISSUE TITLE
nbio with iris framework

### ISSUE THREAD

**Issue by centratelemedia** [lesismal/nbio#275]
any sample how to use nbio with Iris web framework?

**Comment by lesismal** [comment]
Thank you for your attention to nbio!

Can use iris on nbio like this:
```golang
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/kataras/iris/v12"
	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func onHello(ctx iris.Context) {
	ctx.WriteString("hello world")
}

func onWebsocket(ctx iris.Context) {
	upgrader := websocket.NewUpgrader()
	upgrader.OnMessage(func(conn *websocket.Conn, messageType websocket.MessageType, data []byte) {
		// echo
		conn.WriteMessage(messageType, data)
	})
	upgrader.OnOpen(func(conn *websocket.Conn) {
		log.Println("OnOpen:", conn.RemoteAddr().String())
	})

	conn, err := upgrader.Upgrade(ctx.ResponseWriter(), ctx.Request(), nil)
	if err != nil {
		panic(err)
	}
	wsConn := conn.(*websocket.Conn)
	wsConn.OnClose(func(c *websocket.Conn, err error) {
		log.Println("OnClose:", c.RemoteAddr().String(), err)
	})
}

func main() {
	app := iris.New()
	app.Get("/hello", onHello)
	app.Get("/ws", onWebsocket)

	err := app.Build()
	if err != nil {
		panic(err)
	}

	svr := nbhttp.NewServer(nbhttp.Config{
		Network: "tcp",
		Addrs:   []string{"localhost:8080"},
		Handler: app,
	})

	err = svr.Start()
	if err != nil {
		log.Fatalf("nbio.Start failed: %v\n", err)
	}

	log.Println("serving [go-chi/chi] on [nbio]")

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()
	svr.Shutdown(ctx)
}
```

**Comment by lesismal** [comment]
I'll add iris example into nbio-examples later.

**Comment by azzahrah** [comment]
@lesismal 
thanks very much for your attention....
i like nbio... really fast and easy..... i just move from gnet to nbio

mybe you can add feature like ants from gnet

**Comment by centratelemedia** [comment]
@lesismal  thank you verymuch
nbio very fast, i just move from gnet to nbio.... i hope you can add feature like ants from gnet.....

**Comment by lesismal** [comment]
> nbio very fast, i just move from gnet to nbio....

Glad to hear that, thank you so much!

> i hope you can add feature like ants from gnet.....

But ants is not fast....

For more details, please refer to the comments in this issue:
https://github.com/lxzan/gws/issues/3#issuecomment-1447931374

**Comment by centratelemedia** [comment]
i got error, try integrated iris and nbhttp
```

POST: /api/v1/public/login (./server\WebServer.go:41)

2023/03/09 17:02:17.635 [INF] NBIO[NB] start
2023/03/09 17:02:17.643 [INF] Serve  NonTLS On: [tcp@127.0.0.1:8080]
2023/03/09 17:02:17 serving [go-chi/chi] on [nbio]
2023-03-09 17:02:23|0s|404|POST|/api/v1/pubic/login|127.0.0.1|39 B|9 B|{"login":"admin1","password":"zxcvasd"}|
2023/03/09 17:02:23.362 [ERR] conn execute failed: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
github.com/lesismal/nbio.(*Conn).Execute.func1.1.1()
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn.go:123 +0x72
panic({0xe65700, 0x17961b0})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/lesismal/nbio/nbhttp.(*BodyReader).Close(...)
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/nbhttp/body.go:79
github.com/lesismal/nbio/nbhttp.releaseRequest(0xc000c1e000, 0x25?)
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/nbhttp/processor.go:53 +0x11e
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).flushResponse(0xc0000c0230?, 0xc0003a2080)
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/nbhttp/processor.go:290 +0x132
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/nbhttp/processor.go:266 +0x4e
github.com/lesismal/nbio.(*Conn).Execute.func1.1(0xc00000a108?)
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn.go:127 +0x3e
github.com/lesismal/nbio.(*Conn).Execute.func1()
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn.go:128 +0x3e
github.com/lesismal/nbio/taskpool.(*MixedPool).callWitoutRecover(0x1?, 0x0?)
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/taskpool/mixedpool.go:38 +0x59
github.com/lesismal/nbio/taskpool.(*MixedPool).Go.func1()
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/taskpool/mixedpool.go:45 +0x36
created by github.com/lesismal/nbio/taskpool.(*MixedPool).Go
        C:/Users/Joko Pitoyo/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/taskpool/mixedpool.go:44 +0xcd


```
