### ISSUE TITLE
UpgradeAndTransferConnToPoller panics with std http

### ISSUE THREAD

**Issue by elnappo** [lesismal/nbio#354]
If I call while using the std http server UpgradeAndTransferConnToPoller I get a panic:
```go
http: panic serving 127.0.0.1:56186: runtime error: invalid memory address or nil pointer dereference
goroutine 50 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:1868 +0xb0
panic({0x102da8c00?, 0x102fa10d0?})
        /opt/homebrew/opt/go/libexec/src/runtime/panic.go:920 +0x26c
github.com/lesismal/nbio.(*poller).addConn(0x102dfdae8?, 0x14000102340)
        pkg/mod/github.com/lesismal/nbio@v1.3.18/poller_kqueue.go:65 +0x20
github.com/lesismal/nbio.(*Engine).AddConn(0x14000140000, {0x102dfdae8?, 0x14000102340?})
        pkg/mod/github.com/lesismal/nbio@v1.3.18/engine.go:215 +0x70
github.com/lesismal/nbio/nbhttp.(*Engine).AddTransferredConn(0x14000104a00, 0x1400129c000?)
        pkg/mod/github.com/lesismal/nbio@v1.3.18/nbhttp/engine.go:559 +0x278
github.com/lesismal/nbio/nbhttp/websocket.(*Upgrader).Upgrade(0x140001162c0, {0x102dfc000?, 0x1400016a000?}, 0x102ad0ffc?, 0x14000012370?, {0x14000149a98, 0x1, 0x102db7120?})
        pkg/mod/github.com/lesismal/nbio@v1.3.18/nbhttp/websocket/upgrader.go:351 +0xe70
github.com/lesismal/nbio/nbhttp/websocket.(*Upgrader).UpgradeAndTransferConnToPoller(...)
        pkg/mod/github.com/lesismal/nbio@v1.3.18/nbhttp/websocket/upgrader.go:388
main.main.func1({0x102dfc000?, 0x1400016a000?}, 0x14000149ae8?)
        main.go:13 +0x68
net/http.HandlerFunc.ServeHTTP(0x14000149b08?, {0x102dfc000?, 0x1400016a000?}, 0x102c939a8?)
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x102fe0f20?, {0x102dfc000, 0x1400016a000}, 0x14000142300)
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:2514 +0x144
net/http.serverHandler.ServeHTTP({0x1400129a0c0?}, {0x102dfc000?, 0x1400016a000?}, 0x6?)
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x1400129e000, {0x102dfc590, 0x14000100f00})
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 10
        /opt/homebrew/opt/go/libexec/src/net/http/server.go:3086 +0x4cc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102caf798]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0x140000021a0?)
        golang/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x18
main.main()
        main.go:19 +0xf4

Process finished with the exit code 2
```

I guess `IOModNonBlocking` works only with your nbhttp engine? In this case I understand the panic, but maybe it would be more user friendly to return an error instead? Or add a comment to the function?

```go
package main

import (
	"net/http"

	gorilla "github.com/gorilla/websocket"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func main() {
	u := websocket.NewUpgrader()
	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		u.UpgradeAndTransferConnToPoller(w, r, nil)
	})
	go http.ListenAndServe("localhost:8888", nil)

	conn, _, _ := gorilla.DefaultDialer.Dial("ws://localhost:8888/ws", nil)
	defer conn.Close()
}

```

EDIT:
After taking a deeper look into some closed issues, it looks like this should also work with std http? What would be the advantage of using nbhttp?

EDIT2:
`u.Engine.Start()` after `u := websocket.NewUpgrader()` seems to solve it. Is this the recommended way?

**Comment by elnappo** [comment]
Thank you! calling `u.Engine.Start()` after creating the upgrader feels a bit strange but is working fine. I encountered an other issue, the error in `OnClose` is different if the poller is used.

```go
package main

import (
	"fmt"
	"net/http"
	"time"

	gorilla "github.com/gorilla/websocket"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func main() {
	u := websocket.NewUpgrader()
	u.OnClose(func(conn *websocket.Conn, err error) {
		fmt.Println("OnClose:", err)
	})
	u.OnOpen(func(conn *websocket.Conn) {
		fmt.Println("OnOpen:", conn.RemoteAddr())
	})
	u.Engine.Start()
	go http.ListenAndServe("localhost:8888", nil)

	http.HandleFunc("/ws1", func(w http.ResponseWriter, r *http.Request) {
		u.Upgrade(w, r, nil)
	})
	http.HandleFunc("/ws2", func(w http.ResponseWriter, r *http.Request) {
		u.UpgradeAndTransferConnToPoller(w, r, nil)
	})

	conn, _, _ := gorilla.DefaultDialer.Dial("ws://localhost:8888/ws1", nil)
	conn.Close()

	conn, _, _ = gorilla.DefaultDialer.Dial("ws://localhost:8888/ws2", nil)
	conn.Close()

	time.Sleep(time.Second)
}
```
returns:
```
[INF] NBHTTP[NB] Start with "IOModNonBlocking"
[INF] NBIO[NB] start
OnOpen: 127.0.0.1:55998
OnClose: EOF
OnOpen: 127.0.0.1:56000
OnClose: <nil>
```

I would argue that the error should be the same (EOF) in both cases?

**Comment by lesismal** [comment]
> [INF] NBHTTP[NB] Start with "IOModNonBlocking"
> [INF] NBIO[NB] start
> OnOpen: 127.0.0.1:55998
> OnClose: EOF
> OnOpen: 127.0.0.1:56000
> OnClose: <nil>

I tried your code on Linux, but get the same `OnClose: EOF`.
```sh
2023/09/27 16:24:22.073 [INF] NBHTTP[NB] Start with "IOModNonBlocking"
2023/09/27 16:24:22.073 [INF] NBIO[NB] start
OnOpen: 127.0.0.1:49324
OnClose: EOF
OnOpen: 127.0.0.1:49334
OnClose: EOF
```
Would you please provide your golang version and nbio version?

**Comment by elnappo** [comment]
Good to know! Your'e right on Linux it works fine. Tested it with `go1.21.1 darwin/arm64`, `github.com/lesismal/nbio v1.3.18` on macOS Sonoma Version 14.0 (23A344).

**Comment by lesismal** [comment]
Thanks very much for your details!

I've just tried it and found that when the fd is closed by peer, kqueue doesn't return an EOF.
I just made a commit to fix this, please try:
```sh
go get -u github.com/lesismal/nbio@130b7cd
```

details:
https://github.com/lesismal/nbio/commit/130b7cdd9907eb6640ed067307abb7e1c7e721ee

**Comment by elnappo** [comment]
works for me 👍
