### ISSUE TITLE
奇怪得panic

### ISSUE THREAD

**Issue by FJSDS** [lesismal/nbio#445]
线上出现了3个奇怪得panic. 跑了很久了就出现一次  
```
2024-09-21T04:16:19.988776991Z stdout F 2024-09-21 04:16:19.988	ERROR	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:202	conn execute failed: runtime error: invalid memory address or nil pointer dereference

2024-09-21T04:16:19.988779935Z stdout F goroutine 789361 [running]:
2024-09-21T04:16:19.988782056Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1()
2024-09-21T04:16:19.988783874Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:201 +0x6d
2024-09-21T04:16:19.988785405Z stdout F panic({0x14c37c0?, 0x2538050?})
2024-09-21T04:16:19.988787135Z stdout F 	/usr/local/go/src/runtime/panic.go:770 +0x132
2024-09-21T04:16:19.98878922Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close(0xc001acb560)
2024-09-21T04:16:19.98879094Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:57 +0xab
2024-09-21T04:16:19.988792618Z stdout F panic({0x14c37c0?, 0x2538050?})
2024-09-21T04:16:19.988793957Z stdout F 	/usr/local/go/src/runtime/panic.go:770 +0x132
2024-09-21T04:16:19.988795614Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Read(0xc001acb560, {0xc001297800, 0x200, 0x200})
2024-09-21T04:16:19.988797277Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:40 +0x13e
2024-09-21T04:16:19.988798677Z stdout F io.ReadAll({0x7fbecdb89f58, 0xc001acb560})
2024-09-21T04:16:19.988800251Z stdout F 	/usr/local/go/src/io/io.go:712 +0x7e
2024-09-21T04:16:19.988801838Z stdout F noovertime/nbio-gateway/service.(*Service).ginHttpCommon(0xc00022a780, 0xc001b9b500)
2024-09-21T04:16:19.988803376Z stdout F 	/build/nbio-gateway/service/service.go:351 +0xc6
2024-09-21T04:16:19.988804736Z stdout F github.com/gin-gonic/gin.(*Context).Next(...)
2024-09-21T04:16:19.988811833Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
2024-09-21T04:16:19.988813692Z stdout F github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000903d40, 0xc001b9b500)
2024-09-21T04:16:19.988815403Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66e
2024-09-21T04:16:19.98881702Z stdout F github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000903d40, {0x18d8700, 0xc001c80a00}, 0xc00017a5a0)
2024-09-21T04:16:19.988818669Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1b2
2024-09-21T04:16:19.988820006Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
2024-09-21T04:16:19.98882147Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:244 +0x4c
2024-09-21T04:16:19.988823002Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1(0xc0003048c8?)
2024-09-21T04:16:19.988824663Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:208 +0x33
2024-09-21T04:16:19.988826416Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1()
2024-09-21T04:16:19.988828162Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:209 +0x4d
2024-09-21T04:16:19.988830203Z stdout F github.com/lesismal/nbio/taskpool.New.func1(0xc001dfbfb8?)
2024-09-21T04:16:19.988831925Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:84 +0x33
2024-09-21T04:16:19.988833691Z stdout F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1()
2024-09-21T04:16:19.988835601Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:29 +0x64
2024-09-21T04:16:19.988837475Z stdout F created by github.com/lesismal/nbio/taskpool.(*TaskPool).fork in goroutine 97
2024-09-21T04:16:19.988839323Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:27 +0xc5
2024-09-21T04:16:19.988841008Z stdout F 
2024-09-21T04:16:19.988842835Z stdout F 	{"serverId": 0, "serverType": "Gateway"}
2024-09-21T04:16:19.988844357Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1
2024-09-21T04:16:19.98884617Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:202
2024-09-21T04:16:19.98884777Z stdout F runtime.gopanic
2024-09-21T04:16:19.988849858Z stdout F 	/usr/local/go/src/runtime/panic.go:770
2024-09-21T04:16:19.988851712Z stdout F runtime.panicmem
2024-09-21T04:16:19.988853656Z stdout F 	/usr/local/go/src/runtime/panic.go:261
2024-09-21T04:16:19.988855544Z stdout F runtime.sigpanic
2024-09-21T04:16:19.988857478Z stdout F 	/usr/local/go/src/runtime/signal_unix.go:881
2024-09-21T04:16:19.988859362Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close
2024-09-21T04:16:19.98886125Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:57
2024-09-21T04:16:19.988863163Z stdout F runtime.gopanic
2024-09-21T04:16:19.988865136Z stdout F 	/usr/local/go/src/runtime/panic.go:770
2024-09-21T04:16:19.988867023Z stdout F runtime.panicmem
2024-09-21T04:16:19.988868916Z stdout F 	/usr/local/go/src/runtime/panic.go:261
2024-09-21T04:16:19.988870868Z stdout F runtime.sigpanic
2024-09-21T04:16:19.988872717Z stdout F 	/usr/local/go/src/runtime/signal_unix.go:881
2024-09-21T04:16:19.988874571Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Read
2024-09-21T04:16:19.988876479Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:40
2024-09-21T04:16:19.988878375Z stdout F io.ReadAll
2024-09-21T04:16:19.988880371Z stdout F 	/usr/local/go/src/io/io.go:712
2024-09-21T04:16:19.988882372Z stdout F noovertime/nbio-gateway/service.(*Service).ginHttpCommon
2024-09-21T04:16:19.988884251Z stdout F 	/build/nbio-gateway/service/service.go:351
2024-09-21T04:16:19.988886123Z stdout F github.com/gin-gonic/gin.(*Context).Next
2024-09-21T04:16:19.988887986Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
2024-09-21T04:16:19.988889864Z stdout F github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
2024-09-21T04:16:19.988891621Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
2024-09-21T04:16:19.988894997Z stdout F github.com/gin-gonic/gin.(*Engine).ServeHTTP
2024-09-21T04:16:19.988897028Z stdout F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
2024-09-21T04:16:19.988898978Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1
2024-09-21T04:16:19.988900813Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:244
2024-09-21T04:16:19.988902705Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1
2024-09-21T04:16:19.988904515Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:208
2024-09-21T04:16:19.98890654Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1
2024-09-21T04:16:19.988908481Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:209
2024-09-21T04:16:19.988910293Z stdout F github.com/lesismal/nbio/taskpool.New.func1
2024-09-21T04:16:19.988915258Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:84
2024-09-21T04:16:19.988918524Z stdout F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1
2024-09-21T04:16:19.988920281Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:29
2024-09-21T04:16:19.988922283Z stdout F 2024-09-21 04:16:19.988	ERROR	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:202	conn execute failed: runtime error: invalid memory address or nil pointer dereference
2024-09-21T04:16:19.988924268Z stdout F goroutine 789362 [running]:
2024-09-21T04:16:19.988926196Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1()
2024-09-21T04:16:19.98892809Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:201 +0x6d
2024-09-21T04:16:19.988930129Z stdout F panic({0x14c37c0?, 0x2538050?})
2024-09-21T04:16:19.988932071Z stdout F 	/usr/local/go/src/runtime/panic.go:770 +0x132
2024-09-21T04:16:19.988933871Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close(0xc001acb560)
2024-09-21T04:16:19.988935819Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:57 +0xab
2024-09-21T04:16:19.988937645Z stdout F github.com/lesismal/nbio/nbhttp.releaseRequest(0xc001260480, 0xb8?)
2024-09-21T04:16:19.988939629Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:50 +0x55
2024-09-21T04:16:19.988941506Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).flushResponse(0xc000903d40?, 0x18d8700?, 0xc001a13b80)
2024-09-21T04:16:19.988943349Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:271 +0x91
2024-09-21T04:16:19.988945326Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
2024-09-21T04:16:19.98894717Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:245 +0x65
2024-09-21T04:16:19.988949047Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1(0x18c8720?)
2024-09-21T04:16:19.988950978Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:208 +0x33
2024-09-21T04:16:19.988952861Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1()
2024-09-21T04:16:19.988954801Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:209 +0x4d
2024-09-21T04:16:19.988956714Z stdout F github.com/lesismal/nbio/taskpool.New.func1(0x13b4ce5?)
2024-09-21T04:16:19.988958442Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:84 +0x33
2024-09-21T04:16:19.988960269Z stdout F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1()
2024-09-21T04:16:19.988962137Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:29 +0x64
2024-09-21T04:16:19.988964088Z stdout F created by github.com/lesismal/nbio/taskpool.(*TaskPool).fork in goroutine 97
2024-09-21T04:16:19.988966001Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:27 +0xc5
2024-09-21T04:16:19.988967743Z stdout F 
2024-09-21T04:16:19.988969637Z stdout F 	{"serverId": 0, "serverType": "Gateway"}
2024-09-21T04:16:19.988971634Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1
2024-09-21T04:16:19.988976812Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:202
2024-09-21T04:16:19.988978821Z stdout F runtime.gopanic
2024-09-21T04:16:19.988980834Z stdout F 	/usr/local/go/src/runtime/panic.go:770
2024-09-21T04:16:19.988982717Z stdout F runtime.panicmem
2024-09-21T04:16:19.988984657Z stdout F 	/usr/local/go/src/runtime/panic.go:261
2024-09-21T04:16:19.98898658Z stdout F runtime.sigpanic
2024-09-21T04:16:19.98898852Z stdout F 	/usr/local/go/src/runtime/signal_unix.go:881
2024-09-21T04:16:19.988990404Z stdout F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close
2024-09-21T04:16:19.988992261Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/body.go:57
2024-09-21T04:16:19.988994186Z stdout F github.com/lesismal/nbio/nbhttp.releaseRequest
2024-09-21T04:16:19.988996012Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:50
2024-09-21T04:16:19.988997918Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).flushResponse
2024-09-21T04:16:19.988999804Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:271
2024-09-21T04:16:19.989001706Z stdout F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1
2024-09-21T04:16:19.989003626Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/nbhttp/processor.go:245
2024-09-21T04:16:19.989005558Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1
2024-09-21T04:16:19.989007476Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:208
2024-09-21T04:16:19.989009495Z stdout F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1
2024-09-21T04:16:19.989013201Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/conn.go:209
2024-09-21T04:16:19.989016453Z stdout F github.com/lesismal/nbio/taskpool.New.func1
2024-09-21T04:16:19.989020345Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:84
2024-09-21T04:16:19.98902225Z stdout F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1
2024-09-21T04:16:19.989024177Z stdout F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.9/taskpool/taskpool.go:29
```
其中ginHttpCommon得panic得代码如下:

![image](https://github.com/user-attachments/assets/780c4905-d526-48e1-99f9-ba7e8253581b)

从代码和堆栈看存在的表象：
1.看起来像Body为nil. 
2.从第二个第三个panic来看，Body是nil

**Comment by FJSDS** [comment]
自签名双向认证TLS

**Comment by FJSDS** [comment]
server 配置如下
![image](https://github.com/user-attachments/assets/b23a715a-4d38-42fc-88f3-a62f3ffce3ca)

**Comment by lesismal** [comment]
感谢反馈！
看了下代码，有可能是BodyReader的engine为nil导致的，之前request没有body的时候会创建个空的 BodyReader 避免用户像标准库那样不判断nil可能导致问题。但确实奇怪，空的BodyReader剩余为0也会直接返回EOF，不应该会日志里那样走到panic的代码，我先提交、加固了一下设置上engine和初始化其他各个字段为0值：
https://github.com/lesismal/nbio/commit/5ec73322b2bbb89ce930bfc835f9184f2a6a06ad
https://github.com/lesismal/nbio/commit/e9d641bf786791f6f0ca5b0ccdfd59d3eed75a90

**Comment by lesismal** [comment]
尝试了简单例子，没有复现出来（因为已经到了http handler，所以猜测跟tls可能没关系）：
```golang
func onHello(c *gin.Context) {
	defer c.Request.Body.Close()
	b, err := io.ReadAll(c.Request.Body)
	if err != nil {
		panic(err)
	}
	fmt.Println("b:", string(b))
	c.String(http.StatusOK, "hello world")
}
```

如果能稳定复现就好定位了，我再继续看看

**Comment by FJSDS** [comment]
我这里也复现不了了，线上跑了一段时间，就出现了这一次。并且还经常压测，并发都是2W rps以上的量来压，都没遇到过，我再观察观察，我代码也做了加强。应该出现不了了

**Comment by FJSDS** [comment]
暂时先关了吧。后面再出现的话再打开

**Comment by lesismal** [comment]
好的

**Comment by FJSDS** [comment]
这个panic又出现了。研究了一下，应该是websocket和http同时存在有关系
@lesismal 

10月14号出现的情况和10月23号出现的情况一模一样，感觉像websocket升级成功之后又调到了http handler 这边来了
![image](https://github.com/user-attachments/assets/cdf3ab4e-4aed-411d-9d2b-30d1ffe844cf)
![image](https://github.com/user-attachments/assets/9c8e8d25-7ca5-49d3-b5f6-86bb51a117bf)

panic还是两段,和10月14日一样，都是两个 **BodyAllocator.Free** 的地方

```
 F 2024-10-23 15:45:25.663	ERROR	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:202	conn execute failed: runtime error: invalid memory address or nil pointer dereference

 F goroutine 482493 [running]:
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:201 +0x6d
 F panic({0x14ce520?, 0x254f510?})
 F 	/usr/local/go/src/runtime/panic.go:770 +0x132
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close(0xc002602c60)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:57 +0xab
 F panic({0x14ce520?, 0x254f510?})
 F 	/usr/local/go/src/runtime/panic.go:770 +0x132
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Read(0xc002602c60, {0xc001552000, 0x200, 0x200})
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:40 +0x13e
 F io.ReadAll({0x7fa165091818, 0xc002602c60})
 F 	/usr/local/go/src/io/io.go:712 +0x7e
 F noovertime/nbio-gateway/service.(*Service).ginHttpCommon(0xc0001c2780, 0xc0025dc000)
 F 	/build/nbio-gateway/service/service.go:359 +0xe5
 F github.com/gin-gonic/gin.(*Context).Next(...)
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
 F github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001184e0, 0xc0025dc000)
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66e
 F github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001184e0, {0x18e58d8, 0xc0024e6100}, 0xc0025de900)
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1b2
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:248 +0x4c
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1(0x496d6a?)
 F	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:208 +0x33
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:209 +0x4d
 F github.com/lesismal/nbio/taskpool.New.func1(0xc00120cfa0?)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:84 +0x33
 F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:29 +0x64
 F created by github.com/lesismal/nbio/taskpool.(*TaskPool).fork in goroutine 78
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:27 +0xc5
  F 	{"serverId": 0, "serverType": "Gateway"}

// 上面一截堆栈是log error 出来的堆栈
// 下面才是panic堆栈

 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:202
 F runtime.gopanic
 F 	/usr/local/go/src/runtime/panic.go:770
 F runtime.panicmem
 F 	/usr/local/go/src/runtime/panic.go:261
 F runtime.sigpanic
 F 	/usr/local/go/src/runtime/signal_unix.go:881
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:57
 F runtime.gopanic
 F 	/usr/local/go/src/runtime/panic.go:770
 F runtime.panicmem
 F 	/usr/local/go/src/runtime/panic.go:261
 F runtime.sigpanic
 F 	/usr/local/go/src/runtime/signal_unix.go:881
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Read
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:40
 F io.ReadAll
 F 	/usr/local/go/src/io/io.go:712
 F noovertime/nbio-gateway/service.(*Service).ginHttpCommon
 F 	/build/nbio-gateway/service/service.go:359
 F github.com/gin-gonic/gin.(*Context).Next
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
 F github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
 F github.com/gin-gonic/gin.(*Engine).ServeHTTP
 F 	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:248
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:208
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:209
 F github.com/lesismal/nbio/taskpool.New.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:84
 F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:29
```
```
 F 2024-10-23 15:45:25.663	ERROR	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:202	conn execute failed: runtime error: invalid memory address or nil pointer dereference
 F goroutine 482444 [running]:
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:201 +0x6d
 F panic({0x14ce520?, 0x254f510?})
 F 	/usr/local/go/src/runtime/panic.go:770 +0x132
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close(0xc002602c60)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:57 +0xab
 F github.com/lesismal/nbio/nbhttp.releaseRequest(0xc0006af560, 0xb8?)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:50 +0x55
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).flushResponse(0xc0001184e0?, 0x18e58d8?, 0xc00247f900)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:275 +0x91
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:249 +0x65
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1(0x18d5700?)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:208 +0x33
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:209 +0x4d
 F github.com/lesismal/nbio/taskpool.New.func1(0x13bfb05?)
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:84 +0x33
 F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1()
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:29 +0x64
 F created by github.com/lesismal/nbio/taskpool.(*TaskPool).fork in goroutine 76
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:27 +0xc5
 F 
 F 	{"serverId": 0, "serverType": "Gateway"}

 // 上面一截堆栈是log error 出来的堆栈
// 下面才是panic堆栈
 
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1.1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:202
 F runtime.gopanic
 F 	/usr/local/go/src/runtime/panic.go:770
 F runtime.panicmem
 F 	/usr/local/go/src/runtime/panic.go:261
 F runtime.sigpanic
 F 	/usr/local/go/src/runtime/signal_unix.go:881
 F github.com/lesismal/nbio/nbhttp.(*BodyReader).Close
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/body.go:57
 F github.com/lesismal/nbio/nbhttp.releaseRequest
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:50
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).flushResponse
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:275
 F github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/nbhttp/processor.go:249
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1.1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:208
 F github.com/lesismal/nbio.(*Conn).Execute.(*Conn).execute.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/conn.go:209
 F github.com/lesismal/nbio/taskpool.New.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:84
 F github.com/lesismal/nbio/taskpool.(*TaskPool).fork.func1
 F 	/go/pkg/mod/github.com/lesismal/nbio@v1.5.11/taskpool/taskpool.go:29
```


下面是我HTTP handler的代码片段，还是 io.ReadAll的时候诱发的
![image](https://github.com/user-attachments/assets/2991be2f-0595-4939-80fc-ce4c464cedf8)

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/e1dda3d1-a18d-4f15-8745-959ee2321139)
但是我的router不一样啊，websocket 的不应该走过来才对

**Comment by FJSDS** [comment]
我好像发现一个问题,BodyReader 被close多次导致bodyReaderPool.put 了2次
defer 手动close一次
![image](https://github.com/user-attachments/assets/86f50646-50bd-4156-adfd-bcc66706c0ab)

releaseRequest close一次
![image](https://github.com/user-attachments/assets/12f491a3-b1ed-44a0-990a-0c090797ccbd)

**Comment by FJSDS** [comment]
所以我有必要手动 Body.Close吗?

**Comment by lesismal** [comment]
> 所以我有必要手动 Body.Close吗?

应该是不需要手动close, 但close应该也没影响, 不确定是不是bodyreader的bug.
你们的body大概多大? 是不是trailer?我看下能不能复现

**Comment by FJSDS** [comment]
就是我自己再close一次造成的

**Comment by FJSDS** [comment]
已经确定了，就是close多次造成。从panic堆栈和各种情况分析，基本确定就是这个造成的。你的close里面应该加个判断，不然其他人调用了body.close会导致同样的问题，同一个对象往sync.Pool中put了不止一次，必定出问题

**Comment by lesismal** [comment]
确实, 之前只处理了buffer的判断, bodyreader这个结构体本身忽视了, 提交了:
https://github.com/lesismal/nbio/commit/fd8d727db2ad539c6eb7c1020adf9c2047c18b19#diff-95c1224fc9d3edf4f768e8fe77da54c66e87ea68db04e4736f0a5f6e448ad649
https://github.com/lesismal/nbio/commit/fd8d727db2ad539c6eb7c1020adf9c2047c18b19#diff-b2bc8f9cc8273cb9c6314edff880dbf1b29c20d4d603d368c435df1fba2a0e5f

release: https://github.com/lesismal/nbio/releases/tag/v1.5.12

感谢!
